# Generated by Django 3.1.7 on 2021-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
