# Generated by Django 3.1.7 on 2021-04-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_auto_20210419_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
